workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios:
        xcode: latest
        cocoapods: default
        ios_signing:
          automatic_signing:
            enabled: true
            distribution_type: app-store
            bundle_identifier: com.michaelverette.myapp