workflows:
  ios-app:
    name: Build iOS app
    environment:
      xcode: 15.0
      ios_signing:
        distribution_type: development
    scripts:
      - name: Build ipa for iOS
        script: |
          xcode-project build-ipa \
            --project "GeoCards.xcodeproj" \
            --scheme "GeoCards"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your@email.com